JDKB.UI/Controllers/ErrosController.cs
using JDKB.Domain.Contracts.Data;
using JDKB.Domain.Contracts.Repositories;
using JDKB.Domain.Entities;
using JDKB.Helpers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;


namespace JDKB.UI.Controllers
{
    public class ErrosController : Controller
    {
        private readonly INPC_ErroRepository _erroRepo;
        private readonly IUnityOfWork _uow;

        public ErrosController(INPC_ErroRepository erroRepo, IUnityOfWork uow)
        {
            _erroRepo = erroRepo;
            _uow = uow;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.Title = "NPC Erros";

            ViewData["CurrentSort"] = sortOrder;
            ViewData["CodErroSortParm"] = String.IsNullOrEmpty(sortOrder) ? "cod_erro" : "";
            ViewData["DescErroSortParm"] = sortOrder == "Erro" ? "erro_desc" : "Erro";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var data = await _erroRepo.GetAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                data = data.Where(s => s.CD_ERRO.ToUpper().Contains(searchString.ToUpper())
                    || s.DSC_ERRO.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "cod_erro":
                    data = data.OrderByDescending(s => s.CD_ERRO);
                    break;
                case "Erro":
                    data = data.OrderBy(s => s.DSC_ERRO);
                    break;
                case "erro_desc":
                    data = data.OrderByDescending(s => s.DSC_ERRO);
                    break;
                default:
                    data = data.OrderBy(s => s.CD_ERRO);
                    break;
            }

            int pageSize = 20; // Número de registros por Página

            return View(PaginatedList<NPC_Erro>.Create(data.AsQueryable(), pageNumber ?? 1, pageSize));
        }

    }
}

JDKB.UI/Controllers/HomeController.cs
using JDKB.Data.EF;
using JDKB.Domain.Contracts.Data;
using JDKB.Domain.Contracts.Repositories;
using JDKB.Domain.Entities;
using JDKB.Helpers;
using JDKB.UI.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace JDKB.UI.Controllers
{
    public class HomeController : Controller
    {
        //private readonly JDDataContext _ctx;

        private readonly INPC_SituacaoRepository _situacaoRepo;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IAnexoRepository _anexoRepo;
        private readonly IUnityOfWork _uow;

        //public HomeController(JDDataContext ctx)
        //{
        //    _ctx = ctx;
        //}

        public HomeController(INPC_SituacaoRepository situacaoRepo, IHostingEnvironment hostingEnvironment, 
            IAnexoRepository anexoRepo, IUnityOfWork uow)
        {
            _situacaoRepo = situacaoRepo;
            _hostingEnvironment = hostingEnvironment;
            _anexoRepo = anexoRepo;
            _uow = uow;
        }

        //public async Task<IActionResult> Index() => View(await _situacaoRepo.GetAsync());
        public IActionResult Index() => View();

        [HttpGet]
        public IActionResult Add() => View();

        [HttpPost]
        public async Task<IActionResult> Add(NPC_SituacaoAddVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var data = model.ToData();

            _situacaoRepo.Add(data);
            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public async Task<IActionResult> Upload()
        {
            var anexos = await _anexoRepo.GetAsync();

            //return new JsonResult(anexos);
            return View(anexos);
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            if (Request.Form.Files == null || Request.Form.Files.Count == 0)
                return Content("Arquivo não selecionado");

            var anexos = await _anexoRepo.GetAsync();
            int maxId = anexos.DefaultIfEmpty(new Anexo { Id = 0 }).Max(a => a.Id) + 1;
            
            foreach (var item in Request.Form.Files)
            {
                /// Salva o arquivo em memória
                byte[] bytes = new byte[item.Length];

                using (var ms = new MemoryStream(bytes))
                {
                    await item.CopyToAsync(ms);
                    ms.Seek(0, SeekOrigin.Begin);

                    /// Salva em arquivo
                    //var path = Path.Combine("c:\\", "Pessoal\\", file.FileName);
                    //using (var fs = new FileStream(path, FileMode.Create))
                    //{
                    //    await ms.CopyToAsync(fs);
                    //    await fs.FlushAsync();
                    //}

                    /// Salva na Base
                    _anexoRepo.Add(new Anexo
                    {
                        Id = maxId,
                        NomeArquivo = item.FileName,
                        Arquivo = ms.ToArray()
                    });

                    maxId++;
                }
            }

            await _uow.CommitAsync();

            return RedirectToAction("Upload");
        }

        [HttpPost]
        public IActionResult AddImage(List<IFormFile> files)
        {
            //if (files.Count == 0)
            //    return Content("file(s) not selected");

            //List<Anexo> anexos = (List<Anexo>)ViewData["Anexos"];
            //if (anexos == null)
            //{
            //    anexos = new List<Anexo>();
            //    ViewData["Anexos"] = anexos;
            //}

            foreach (var file in Request.Form.Files)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    ms.Seek(0, SeekOrigin.Begin);

                    //anexos.Add(new Anexo
                    //{
                    //    NomeArquivo = file.FileName,
                    //    Arquivo = ms.ToArray()
                    //});

                }
            }

            //IFormFile anexos = model.Anexos; //(List<Anexo>)ViewData["Anexos"];
            //if (anexos == null)
            //{
            //    //anexos = new List<Anexo>();
            //    model.Anexos = anexos; //new IFormFile;
            //    //ViewData["Anexos"] = anexos;
            //}

            //foreach (var file in Request.Form.Files)
            //{

            //using (var ms = new MemoryStream())
            //{
            //    //file.CopyTo(ms);
            //    //ms.Seek(0, SeekOrigin.Begin);                                 

            //}
            //}

            return View("Upload", ViewData);
        }

        [HttpGet]
        public async Task<IActionResult> Download(int id)
        {
            var anexo = await _anexoRepo.GetAsync(id);

            //var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot" + "/UserFiles/files/", filename);

            var memory = new MemoryStream();
            using (var ms = new MemoryStream(anexo.Arquivo))
            {
                await ms.CopyToAsync(memory);
                memory.Seek(0, SeekOrigin.Begin);                
            }
            
            return File(memory, anexo.NomeArquivo.GetMimeType(), Path.GetFileName(anexo.NomeArquivo));
        }

        //private string GetContentType(string path)
        //{
        //    var types = GetMimeTypes();
        //    var ext = Path.GetExtension(path).ToLowerInvariant();

        //    return types[ext];
        //}

        //private Dictionary<string, string> GetMimeTypes()
        //{
        //    return new Dictionary<string, string>
        //    {
        //        {".png", "image/png"},
        //        {".jpg", "image/jpeg"},
        //        {".jpeg", "image/jpeg"},
        //        {".gif", "image/gif"},
        //        {".svg", "image/svg+xml"},
        //        {".xml", "image/svg+xml"},
        //        {".txt", "text/plain"},
        //        {".docx", "text/plain"},
        //        {".doc", "text/plain"}
        //    };
        //}

    }
}

JDKB.UI/Views/Home/Add.cshtml
@model NPC_SituacaoAddVM

@{
    ViewData["Title"] = "Add";
}

<h3>Adicionar Situação</h3>

<form method="post">

    <div class="form-group">
        <label asp-for="CD_OBJETO"></label>
        <input class="form-control" asp-for="@Model.CD_OBJETO" autofocus>
    </div>

    <div class="form-group">
        <label asp-for="CD_SITUACAO"></label>
        <input class="form-control" asp-for="@Model.CD_SITUACAO" autofocus>
    </div>

    <div class="form-group">
        <label asp-for="DSC_SITUACAO"></label>
        <input class="form-control" asp-for="@Model.DSC_SITUACAO" autofocus>
    </div>

    <div>
        <button class="btn btn-outline-info" type="submit">Salvar</button>
        <a class="btn btn-outline-danger" asp-action="Index" asp-controller="Home">Voltar</a>
    </div>

</form>

JDKB.UI/Views/Home/Index.cshtml
@model IEnumerable<NPC_Situacao>

@{
    ViewData["Title"] = "JD - KnowledgeBase";
}

    <div style="position:relative; text-align:center">
        <div>
            <img src="~/images/Logo.png" alt="JD Consultores" class="img-thumbnail img-fluid" style="ima" />
            <span style="font-size:30px">JD Base de Conhecimento</span>
        </div>
    </div>
    

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div>
    <a class="btn btn-outline-secondary" asp-action="Add" asp-controller="Home">Adicionar</a>
    <a class="btn btn-outline-secondary" asp-action="Index" asp-controller="Erros">Erros</a><br />

    <table id="dtBasicExample" class="table table-striped table-hover table-bordered table-sm" cellspacing="0" width="100%">
        <thead class="thead-dark">
            <tr>
                <th>Objeto</th>
                <th>Situação</th>
                <th>Descrição</th>
            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CD_OBJETO</td>
                    <td>@item.CD_SITUACAO</td>
                    <td>@item.DSC_SITUACAO</td>
                </tr>
            }

        </tbody>

    </table>
</div>*@

JDKB.UI/Views/Home/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}

@model IEnumerable<JDKB.Domain.Entities.Anexo>

<style>

    .dropzone {
        margin-bottom: 10px;
        border: dashed;
        min-height: 250px;
    }

</style>

<style>
    a, a:hover {
        color: #1a0dab;
    }

    span {
        color: #dc3545; /*#006621;*/
    }

    mark, .mark {
        padding: 0;
        background-color: yellow;
    }

    .search_conteudo {
        font-size: small;
        line-height: 1.4;
        word-wrap: break-word;
    }

    h2 {
        font-size: 18px;
        margin-top: 10px;
        margin-bottom: 0px;
    }

    .tags {
        font-size: x-small;
        margin-bottom: 5px;
        color: darkblue; /*#006621;*/
    }

    .resultStats {
        color: #808080;
    }

    .small, small {
        font-size: 90%;
    }

    #pesquisa {
        border-radius: 3rem;
        padding: 1rem;
    }

    .form-signin .btn {
        border-radius: 3rem;        
    }

    .form-control {
        font-size:14px;
    }

    .rounded {
        border-radius: 3rem !important;
    }

</style>

<label for="Anexos" class="control-label col-sm-1">Anexos</label>

<form id="frmUpload" asp-controller="Home" asp-action="AddImage" enctype="multipart/form-data" method="POST">
    <div class="dropzone" id="my-dropzone" name="mainFileUploader">
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </div>
</form>

<div>
    <button type="submit" id="submit-all"> upload </button>
</div>
<br />

<h2>Arquivos</h2>
<div>
    <table id="Table" class="table table-striped table-hover table-bordered table-sm mt-4" cellspacing="0" width="100%">
        <thead class="thead-dark">
            <tr>
                <th>Arquivo</th>
                <th>Id</th>
            </tr>
        </thead>

        <tbody>

            @foreach (var anexo in Model)
            {
                <tr>
                    <td>
                        <a name="@anexo.Arquivo" asp-action="Download" asp-controller="Home" asp-route-id="@anexo.Id">@anexo.NomeArquivo</a>
                    </td>
                    <td>@anexo.Id</td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script src="~/lib/dropzone/dropzone.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>

    //$(document).ready(function () {

    //    $.ajax({
    //        type: 'GET',
    //        url: '/Home/Upload',
    //        //contentType: "application/html; charset=utf-8",  
    //        //dataType: "html",  
    //        success: function (data) {  

    //            //alert(JSON.stringify(data));                  
    //            //$("#DIV").html('');   
    //            //var DIV = '';  

    //            $.each(data, function (i, item) {  
    //                var rows = "<tbody><tr>" +  
    //                    "<td id='Arquivo'>" + item.Arquivo + "</td>" +  
    //                    "<td id='Id'>" + item.Id + "</td>" +    
    //                    "</tr></tbody>";  
    //                $('#Table').append(rows);  
    //            });
                
    //            console.log(data);  
    //        },
  
    //        failure: function (data) {  
    //            alert(data.responseText);  
    //        },

    //        error: function (data) {  
    //            alert(data.responseText);  
    //        }
    //    });

    //});

    function Enviar() {
        $("form#frmUpload").submit();
    };

    Dropzone.options.myDropzone = {
        url: "/Home/UploadFile",
        autoProcessQueue: false,
        uploadMultiple: true,
        parallelUploads: 100,
        maxFiles: 100,
        acceptedFiles: "image/*,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/docx,application/msword",
        addRemoveLinks: true,
        dictDefaultMessage: "<strong>Arraste os arquivos aqui ou clique para upload.</strong>",

        init: function () {

            var submitButton = document.querySelector("#submit-all");
            var wrapperThis = this;

            submitButton.addEventListener("click", function () {
                wrapperThis.processQueue();
            });

            this.on("complete", function (data) {
                $(".dz-remove").html("<div><span class='fa fa-trash text-danger' style='font-size: 1.5em'></span></div>");
            });

            this.on("maxfilesexceeded", function (file) {
                this.removeFile(file);
            });

            //this.on("addedfile", function (file) {

            //    // Create the remove button
            //    var removeButton = Dropzone.createElement("<button class='btn btn-lg dark'>Remover</button>");

            //    // Listen to the click event
            //    removeButton.addEventListener("click", function (e) {
            //        // Make sure the button click doesn't submit the form:
            //        e.preventDefault();
            //        e.stopPropagation();

            //        // Remove the file preview.
            //        wrapperThis.removeFile(file);
            //        // If you want to the delete the file on the server as well,
            //        // you can do the AJAX request here.
            //    });

            //    // Add the button to the file preview element.
            //    file.previewElement.appendChild(removeButton);
            //});

            //this.on('sendingmultiple', function (data, xhr, formData) {
            //    formData.append("Username", $("#Username").val());
            //});
        }
    };
</script>