JDKB.UI/Controllers/TipoVisualizacaoController.cs
using JDKB.Domain.Contracts.Data;
using JDKB.Domain.Contracts.Repositories;
using JDKB.Domain.Entities;
using JDKB.Helpers;
using JDKB.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace JDKB.UI.Controllers
{
    public class TipoVisualizacaoController : Controller
    {
        private readonly ITipoVisualizacaoRepository _tipovisualRepo;
        private readonly IUnityOfWork _uow;

        public TipoVisualizacaoController(ITipoVisualizacaoRepository tipovisualRepo, IUnityOfWork uow)
        {
            _tipovisualRepo = tipovisualRepo;
            _uow = uow;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.Title = "Tipo Visualização";

            ViewData["CurrentSort"] = sortOrder;
            ViewData["TipoVisualSortParm"] = String.IsNullOrEmpty(sortOrder) ? "tipo_visual" : "";
            ViewData["DescTipoVisualSortParm"] = sortOrder == "Tipo" ? "tipovisual_desc" : "Tipo";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var tipovisual = await _tipovisualRepo.GetAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                tipovisual = tipovisual.Where(s => s.Tipo.ToUpper().Contains(searchString.ToUpper())
                    || s.Descricao.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "tipo_visual":
                    tipovisual = tipovisual.OrderByDescending(s => s.Tipo);
                    break;
                case "Tipo":
                    tipovisual = tipovisual.OrderBy(s => s.Descricao);
                    break;
                case "tipovisual_desc":
                    tipovisual = tipovisual.OrderByDescending(s => s.Descricao);
                    break;
                default:
                    tipovisual = tipovisual.OrderBy(s => s.Descricao);
                    break;
            }

            int pageSize = 20; // Número de registros por Página

            return View(PaginatedList<TipoVisualizacao>.Create(tipovisual.AsQueryable(), pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(string id)
        {
            ViewBag.IsEditing = "N";
            var title = "Adicionar";

            TipoVisualizacaoAddEditVM model = null;

            if (!String.IsNullOrEmpty(id))
            {
                var data = await _tipovisualRepo.GetAsync(id);
                if (data == null) return NotFound();

                model = data.ToVM();
                title = "Editar";
                ViewBag.IsEditing = "S";
            }

            ViewBag.Title = $"{title} Tipo Visualização";

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(string id, TipoVisualizacaoAddEditVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var data = model.ToData();

            if (String.IsNullOrEmpty(id))
            {
                _tipovisualRepo.Add(data);
            }
            else
            {
                _tipovisualRepo.Update(data);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public async Task<IActionResult> Excluir(string id)
        {
            var tipovisual = await _tipovisualRepo.GetAsync(id);

            if (tipovisual == null) return BadRequest();

            _tipovisualRepo.Remove(tipovisual);
            await _uow.CommitAsync();

            return Ok();
        }
    }
}

JDKB.UI/Views/TipoVisualizacao/AddEdit.cshtml
@model TipoVisualizacaoAddEditVM

<h3>@ViewBag.Title</h3>

<form method="post">

    <div class="form-group mt-4">
        <label asp-for="Tipo"></label>
        @if (ViewBag.IsEditing == "S")
        {
            <input class="form-control" asp-for="@Model.Tipo" readonly autofocus>
        }
        else
        {
            <input class="form-control" asp-for="@Model.Tipo" autofocus>
            <span asp-validation-for="Tipo" class="text-danger"></span>
        }
    </div>

    <div class="form-group">
        <label asp-for="DescTipo"></label>
        <input class="form-control" asp-for="@Model.DescTipo" autofocus>
        <span asp-validation-for="DescTipo" class="text-danger"></span>
    </div>

    <div>
        <button class="btn btn-outline-info" type="submit">Salvar</button>
        <a class="btn btn-outline-danger" asp-action="Index" asp-controller="TipoVisualizacao">Cancelar</a>
    </div>

</form>

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

JDKB.UI/Views/TipoVisualizacao/Index.cshtml
@model PaginatedList<TipoVisualizacao>
@using JDKB.Helpers

<h2>@ViewBag.Title</h2>

<div class="mt-4">

    <form asp-action="Index" method="get">
        <div class="input-group">
            <input type="text" name="SearchString" class="form-control" placeholder="Pesquisar por..." aria-label="Pesquisa" aria-describedby="basic-addon2" value="@ViewData["CurrentFilter"]">
            <div class="input-group-append">
                <input type="submit" value="Localizar" class="btn btn-primary" />
                @*<a asp-action="Index" class="btn btn-outline-primary">Limpar Pesquisa</a>*@
                <a asp-action="AddEdit" asp-controller="TipoVisualizacao" class="btn btn-danger">+</a>
            </div>
        </div>
    </form>

    @*<div class="mt-4">
            <a class="btn btn-outline-info" asp-action="AddEdit" asp-controller="TipoVisualizacao">Adicionar</a>
        </div>*@

    <table class="table table-striped table-hover table-bordered table-sm mt-4" cellspacing="0" width="100%">
        <thead class="thead-dark">
            <tr>
                <th>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewData["TipoVisualSortParm"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]" style="color:white">Tipo</a>
                </th>
                <th>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewData["DescTipoVisualSortParm"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]" style="color:white">Descrição</a>
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var tipo in Model)
            {
                <tr id="tipovisual-@tipo.Tipo">
                    <td>@tipo.Tipo</td>
                    <td>@tipo.Descricao</td>
                    <td>
                        <a asp-action="AddEdit" asp-controller="TipoVisualizacao" asp-route-id="@tipo.Tipo" class="btn btn-sm btn-outline-info">Editar</a>
                        <button class="btn btn-sm btn-outline-danger" onclick="delModal('@tipo.Tipo', '@tipo.Descricao')">Excluir</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @*Controle dos botões da paginação*@
    @{
        var firstDisabled = Model.FirstPage ? "disabled" : "";
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        var lastDisabled = Model.LastPage ? "disabled" : "";
    }

    @*Botões da paginação*@
    <div class="mt-3" style="position:relative; text-align:center;">
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="1"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-outline-primary @firstDisabled">
            |<<
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-outline-primary @prevDisabled">
            <
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-outline-primary @nextDisabled">
            >
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@Model.TotalPages"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-outline-primary @lastDisabled">
            >>|
        </a>
    </div>

</div>

<partial name="_delModal" />

<script>
    let data = {};
    data.urlDel = '@Url.Action("Excluir","TipoVisualizacao")';
    data.dataTipo = 'Tipo de Visualizacao';
    data.trId = "tipovisual";
</script>

@section scripts {
    <script src="~/js/delModal.js"></script>
}