JDKB.UI/Controllers/BaseConhecimentoController.cs
using JDKB.Domain.Contracts.Data;
using JDKB.Domain.Contracts.Repositories;
using JDKB.Domain.Entities;
using JDKB.Helpers;
using JDKB.UI.Models;
using JDKB.UI.Models.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JDKB.UI.Controllers
{
    public class BaseConhecimentoController : Controller
    {
        private readonly IBaseConhecimentoRepository _baseconhecimentoRepo;
        private readonly ITipoVisualizacaoRepository _tipovisualizacaoRepo;
        private readonly ISituacaoBaseRepository _situacaobaseRepo;
        private readonly IProdutoRepository _produtoRepo;
        private readonly IBuscaChaveRepository _buscachaveRepo;
        private readonly IPalavraChaveRepository _palavrachaveRepo;
        private readonly IUnityOfWork _uow;

        public BaseConhecimentoController(IBaseConhecimentoRepository baseconhecimentoRepo,
            ITipoVisualizacaoRepository tipovisualizacaoRepo,
            ISituacaoBaseRepository situacaobaseRepo,
            IProdutoRepository produtoRepo,
            IBuscaChaveRepository buscachaveRepo,
            IPalavraChaveRepository palavrachaveRepo,
            IUnityOfWork uow)
        {
            _baseconhecimentoRepo = baseconhecimentoRepo;
            _tipovisualizacaoRepo = tipovisualizacaoRepo;
            _situacaobaseRepo = situacaobaseRepo;
            _produtoRepo = produtoRepo;
            _buscachaveRepo = buscachaveRepo;
            _palavrachaveRepo = palavrachaveRepo;
            _uow = uow;
        }

        public async Task<IActionResult> Index(string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.Title = "Base de Conhecimento";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var searchArray = new string[] { };
            if (!String.IsNullOrEmpty(searchString))
            {
                searchArray = searchString.RemoveAccents().KeyWordToArray();
                searchArray = Array.ConvertAll(searchArray, d => d.ToLower());
            }

            // Verifica se existe usuário logado
            var userId = !string.IsNullOrEmpty(HttpContextHelper.GetAuthUserId(HttpContext)) ? Convert.ToDecimal(HttpContextHelper.GetAuthUserId(HttpContext)) : 0;

            int pageSize = 10; // Número de registros por Página                 

            var data = await _baseconhecimentoRepo.GetWithBaseChildsAsync(searchArray, userId, pageNumber ?? 1, pageSize);

            int total = data.Select(c => c.TotalMath).FirstOrDefault();

            return View(PaginatedList<BaseConhecimento>.Create(data.AsQueryable(), pageNumber ?? 1, pageSize, total));
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(decimal? id)
        {
            if (!User.Identity.IsAuthenticated && id == null)
            {
                return RedirectToAction("SignIn", "Auth");
            }

            ViewBag.IsEditing = "N";

            BaseConhecimentoAddEditVM model = null;

            if (id != null)
            {
                var data = await _baseconhecimentoRepo.GetWithBaseChildsAsync(id);
                if (data == null) return NotFound();

                model = data.ToVM();
                ViewBag.IsEditing = "S";
            }

            await getTipoVisualizacaoSelect();
            await getSituacaoBaseSelect();
            await getProdutosBaseSelect();

            return View(model);
        }

        private async Task getTipoVisualizacaoSelect()
        {
            var tipovisual = await _tipovisualizacaoRepo.GetAsync();

            ViewBag.TiposDeVisualizacao =
                            tipovisual.Select(c => new SelectListItem
                            {
                                Value = c.Tipo,
                                Text = c.Descricao
                            });
        }

        private async Task getSituacaoBaseSelect()
        {
            var situacao = await _situacaobaseRepo.GetAsync();

            ViewBag.SituacaoDaBase =
                            situacao.Select(c => new SelectListItem
                            {
                                Value = c.Situacao,
                                Text = c.Descricao
                            });
        }

        private async Task getProdutosBaseSelect()
        {
            var produto = await _produtoRepo.GetAsync();

            ViewBag.ProdutoDaBase =
                            produto.Select(c => new SelectListItem
                            {
                                Value = c.IdProduto.ToString(),
                                Text = c.NmProduto
                            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddEdit(decimal id, BaseConhecimentoAddEditVM model)
        {
            ModelState.Remove("IdUsuarioRegistro");
            ModelState.Remove("DataHoraRegistro");
            ModelState.Remove("SitBase");

            ViewBag.IsEditing = "N";
            if (id > 0)
            {
                ModelState.Remove("PalavraChave");
                ViewBag.IsEditing = "S";
            }

            if (!ModelState.IsValid)
            {
                await getTipoVisualizacaoSelect();
                await getSituacaoBaseSelect();
                await getProdutosBaseSelect();

                return View(model);
            }

            var userContext = Convert.ToDecimal(HttpContextHelper.GetAuthUserId(HttpContext));

            var data = model.ToData(userContext, id);

            if (id == 0)
            {
                data.DtHrRegistro = Convert.ToDecimal(DateTime.Now.ToString("yyyyMMddHHmmss"));
                data.StBase = EnumHelper.SituacaoBase.BA9.ToString();

                _baseconhecimentoRepo.Add(data);

                // Palavras Chave existentes
                var words = model.PalavraChave.KeyWordToArray();

                // Lista das palavras chave que foram informadas
                var wordID = new List<decimal>();

                // Verifica se a Palavra Chave informada já existe na tabela
                var wordsData = await _palavrachaveRepo.GetAsync();

                foreach (var word in words)
                {
                    decimal IdWord = wordsData
                        .Where(c => c.Palavra.ToUpper() == word.ToUpper())
                        .Select(c => c.IdPalavra).FirstOrDefault();

                    if (IdWord == 0)
                    {
                        // Cria a nova palavra chave
                        var plvr = new PalavraChave()
                        {
                            Palavra = word,
                            IdUsuarioRegistro = data.IdUsuarioRegistro
                        };

                        _palavrachaveRepo.Add(plvr);

                        wordID.Add(plvr.IdPalavra);
                    }
                    else
                    {
                        wordID.Add(IdWord);
                    }
                }

                // Busca Chave
                foreach (var word in wordID)
                {
                    _buscachaveRepo.Add(new BuscaChave()
                    {
                        Id = data.Id,
                        IdPalavra = word,
                        IdUsuarioRegistro = data.IdUsuarioRegistro
                    });
                }
            }
            else
            {
                _baseconhecimentoRepo.Update(data);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }

        public IActionResult About() => View();
    }
}

JDKB.UI/Views/BaseConhecimento/About.cshtml
@inject JDKB.Domain.Contracts.IAppVersionService AppVersionService

<style>

    :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }

    body {
        background: #BD2424;
        background: linear-gradient(to right, #BD2424, #EB6F6F);
    }

    .card-signin {
        border: 0;
        border-radius: 1rem;
        box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .card-signin .card-title {
        margin-bottom: 2rem;
        font-weight: 300;
        font-size: 1.5rem;
    }

    .card-signin .card-body {
        padding: 2rem;
    }

    .form-signin {
        width: 100%;
    }

    .form-signin .btn {
        font-size: 80%;
        border-radius: 5rem;
        letter-spacing: .1rem;
        font-weight: bold;
        padding: 1rem;
        transition: all 0.2s;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }

    .form-label-group > input,
    .form-label-group > label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }

    .form-label-group > label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }

    a, a:hover {
        color: darkred
    }
</style>

<h2>@ViewBag.Title</h2>
<br />

<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">

                    <div class="card-body">
                        <div class="containerlogojd" style="display:inline-block;float:left;">
                            <img src="~/images/Logo.png" />
                        </div>

                        <h5 class="card-title text-center" style="color:#BD2424"><strong>Sobre</strong></h5>

                        <div class="container" style="text-align:center;display:inline-block">
                            <h2><span>@AppVersionService.Product</span></h2>
                        </div>

                        <div class="card-text ">
                            <div class="custom-control" style="display:inline-block">
                                <span>
                                    <i class="zmdi zmdi-balance"></i>
                                </span>
                                Companhia :
                            </div>
                            <div class="mt-4" style="text-align:left;display:inline-block;">
                                <a href="https://www.jdconsultores.com.br">@AppVersionService.Company</a>
                            </div>

                            <div class="custom-control">
                                <span>
                                    <i class="zmdi zmdi-file"></i>
                                </span>
                                Versão : @AppVersionService.Version
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

JDKB.UI/Views/BaseConhecimento/AddEdit.cshtml
@model BaseConhecimentoAddEditVM

@{ 
    decimal SeqVersao = (Model != null) ? Model.SeqVersao : -1;
    bool IsAuth = User.Identity.IsAuthenticated;
    string userContext = User.Claims.Count() > 0 ? User.Claims.Where(c => c.Type == "id").FirstOrDefault().Value : "-1";
}

<h2>@ViewBag.Title</h2>

<form id="formAddEditBC" method="post">

    <input type="hidden" asp-for="@SeqVersao">
    <input type="hidden" name="IdUsuarioRegistro" value="@Model?.IdUsuarioRegistro" />
    <input type="hidden" name="DataHoraRegistro" value="@Model?.DataHoraRegistro" />
    <input type="hidden" name="SitBase" value="@Model?.SitBase" />

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold">Título</label>

        @if (IsAuth && (ViewBag.IsEditing == "N" || ViewBag.IsEditing == "S" && userContext == Model?.IdUsuarioRegistro.ToString()))
        {
            <input class="form-control col-sm-12" asp-for="@Model.Titulo" autofocus>
            <span asp-validation-for="Titulo" class="text-danger"></span>
        }
        else
        {
            <span class="form-text">@Model.Titulo</span>
        }

    </div>

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold">Palavra(s) Chave</label>

        @if (IsAuth && ViewBag.IsEditing == "N")
        {
            <input class="form-control col-sm-12" asp-for="@Model.PalavraChave" autofocus>
            <span asp-validation-for="PalavraChave" class="text-danger"></span>
        }
        else
        {
            <span class="form-text">@Model.PalavraChave</span>
        }

    </div>

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold" asp-for="Produto"></label>

        @if (IsAuth && ViewBag.IsEditing == "N")
        {
            <select class="form-control col-sm-12" asp-for="Produto" asp-items="ViewBag.ProdutoDaBase">
                <option value="">Selecione...</option>
            </select>
            <span asp-validation-for="Produto" class="text-danger"></span>
        }
        else
        {
            <select readonly="readonly" tabindex="-1" aria-disabled="true" class="form-control col-sm-12" asp-for="Produto" asp-items="ViewBag.ProdutoDaBase">
                <option value="">Selecione...</option>
            </select>
        }

    </div>

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold" asp-for="TpVisualizacao"></label>

        @if (IsAuth && (ViewBag.IsEditing == "N" || ViewBag.IsEditing == "S" && userContext == Model?.IdUsuarioRegistro.ToString()))
        {
            <select class="form-control" asp-for="TpVisualizacao" asp-items="ViewBag.TiposDeVisualizacao">
                <option value="">Selecione...</option>
            </select>
            <span asp-validation-for="TpVisualizacao" class="text-danger"></span>
        }
        else
        {
            <select readonly="readonly" class="form-control" asp-for="TpVisualizacao" asp-items="ViewBag.TiposDeVisualizacao">
                <option value="">Selecione...</option>
            </select>
        }

    </div>

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold">Resumo</label>

        @if (IsAuth && (ViewBag.IsEditing == "N" || ViewBag.IsEditing == "S" && userContext == Model?.IdUsuarioRegistro.ToString()))
        {
            <textarea style="height:250px;width:900px" asp-for="@Model.TextoResumo" class="summernote col-sm-12"></textarea>
            <span asp-validation-for="TextoResumo" class="text-danger"></span>            
        }
        else
        {
            <p>@Html.Raw(Model.TextoResumo)</p>
        }

    </div>

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold">Causa Raiz</label>

        @if (IsAuth && (ViewBag.IsEditing == "N" || ViewBag.IsEditing == "S" && userContext == Model?.IdUsuarioRegistro.ToString()))
        {
            <textarea id="areaCausaRaiz" style="display:none;" asp-for="@Model.TextoCausaRaiz" class="summernote col-sm-12"></textarea>
            <span asp-validation-for="TextoCausaRaiz" class="text-danger"></span>            
        }
        else
        {
            <p>@Html.Raw(Model.TextoCausaRaiz)</p>
        }

    </div>

    <div class="form-group mt-4">
        <label class="control-label font-weight-bold">Solução Paliativa</label>

        @if (IsAuth && (ViewBag.IsEditing == "N" || ViewBag.IsEditing == "S" && userContext == Model?.IdUsuarioRegistro.ToString()))
        {
            <textarea style="height:250px;width:900px" asp-for="@Model.TextoSolucaoPaliativa" class="summernote col-sm-12"></textarea>
            <span asp-validation-for="TextoSolucaoPaliativa" class="text-danger"></span>            
        }
        else
        {
            <p>@Html.Raw(Model.TextoSolucaoPaliativa)</p>
        }

    </div>

    <div>
        @if (IsAuth && (ViewBag.IsEditing == "N" || ViewBag.IsEditing == "S" && userContext == Model?.IdUsuarioRegistro.ToString()))
        {
            <button class="btn btn-outline-info mt-2" type="submit">Salvar</button>
            <a class="btn btn-outline-danger mt-2" asp-action="Index" asp-controller="BaseConhecimento">Cancelar</a>
        }
        else
        {
            @*<a class="btn btn-outline-danger mt-2" asp-action="Index" asp-controller="BaseConhecimento">Voltar</a>*@
            <a class="btn btn-outline-danger mt-2" href="javascript:history.back()">Voltar</a>
        }

    </div>

</form>


@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

JDKB.UI/Views/BaseConhecimento/Index.cshtml
@model PaginatedList<BaseConhecimento>
@using JDKB.Helpers
    
    <style>
        a, a:hover {
            color: #1a0dab;
        }

        span {
            color: #dc3545; /*#006621;*/
        }

        mark, .mark {
            padding: 0;
            background-color: yellow;
        }

        .search_conteudo {
            font-size: small;
            line-height: 1.4;
            word-wrap: break-word;
        }

        h2 {
            font-size: 18px;
            margin-top: 10px;
            margin-bottom: 0px;
        }

        .tags {
            font-size: x-small;
            margin-bottom: 5px;
            color: darkblue; /*#006621;*/
        }

        .resultStats {
            color: #808080;
        }

        .small, small {
            font-size: 90%;
        }

    </style>

    <div class="mt-4">

        <form asp-action="Index" method="get">
            <div class="input-group">
                <input type="text" name="SearchString" class="form-control shadow-sm bg-white rounded-left" placeholder="Pesquisar por..."
                       aria-label="Pesquisa" aria-describedby="basic-addon2" value="@ViewData["CurrentFilter"]">

                <div class="input-group-append shadow-sm">
                    <input type="submit" value="Localizar" class="btn btn-primary" />

                    @if (User.Identity.IsAuthenticated)
                    {
                        <a asp-action="AddEdit" asp-controller="BaseConhecimento" class="btn btn-danger shadow-sm rounded-right"><span class="glyphicon glyphicon-plus-sign"></span>+</a>
                    }

                </div>

            </div>

        </form>

        <div class="col-md-11 col-xs-12 col-sm-12 mt-4" style="padding-left: 0px;">

            <div class="search_conteudo mt-4">

                @*Texto com o Resultado da Busca*@
                @{
                    if (Model.TotalItens == 0)
                    {
                        <small class="resultStats"><i>Nenhum resultado encontrado</i></small>
                    }
                    else if (Model.TotalItens == 1)
                    {
                        <small class="resultStats">Foi encontrado 1 resultado</small>
                    }
                    else
                    {
                        <small class="resultStats">Foram encontrados @Model.TotalItens.ToString() resultados</small>
                    }
                }

                @foreach (var item in Model)
                {
                    // Título
                    <h2>
                        <a asp-action="AddEdit" asp-controller="BaseConhecimento" asp-route-id="@item.Id">
                            @Html.Raw(item.Resumo.Select(t => t.DsTitulo).FirstOrDefault())
                        </a>
                    </h2>

                    // Palavra(s) chave
                    <div class="tags">
                        @*<span>*@
                            @Html.Raw(item.BuscaChave.Select(t => t.Tags.SplitText(x => x)).FirstOrDefault())
                        @*</span>*@
                    </div>

                    // Conteúdo do Resumo
                    <div class="search_conteudo" style="font-size:small">
                        @Html.Raw(item.Resumo.Select(r => r.Texto).FirstOrDefault())
                    </div>

                    // Produto
                    <div>
                        <p class="text-right" style="font-size: x-small; color: #777">
                            Produto: @item.BaseProduto.Select(e => e.Produto.NmProduto).FirstOrDefault()
                        </p>
                    </div>
                }
            </div>

        </div>

        @*Controle dos botões da paginação*@
        @{
            var firstDisabled = Model.FirstPage ? "disabled" : "";
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            var lastDisabled = Model.LastPage ? "disabled" : "";
        }

        @*Botões da paginação*@
        <div class="col-md-offset-6 mt-5" style="position:relative; text-align:center;">
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="1"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-outline-primary @firstDisabled">
                |<<
            </a>
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex - 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-outline-primary @prevDisabled">
                <
            </a>
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(Model.PageIndex + 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-outline-primary @nextDisabled">
                >
            </a>
            <a asp-action="Index"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@Model.TotalPages"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="btn btn-outline-primary @lastDisabled">
                >>|
            </a>
        </div>

    </div>

 