JDKB.UI/Controllers/AuthController.cs
using JDKB.Domain.Contracts;
using JDKB.Domain.Contracts.Data;
using JDKB.Domain.Contracts.Repositories;
using JDKB.Domain.Entities;
using JDKB.Email;
using JDKB.Helpers;
using JDKB.UI.Models;
using log4net;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace JDKB.UI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepo;
        private readonly IUnityOfWork _uow;
        private readonly ICustomAppSettings _credential;
        public AuthController(IUsuarioRepository usuarioRepo, ICustomAppSettings credential,
            ILogger<AuthController> logger, IUnityOfWork uow)
        {
            _usuarioRepo = usuarioRepo;
            _uow = uow;
            _credential = credential;
        }

        [HttpGet]
        public IActionResult SignIn() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn(string returnUrl, SignInVM model)
        {
            var usuario = await _usuarioRepo.AuthenticateAsync(model.Email, model.Senha.Encrypt());

            if (usuario == null)
            {
                ModelState.AddModelError("", "Email e/ou Senha inválidos");
                return View(model);
            }

            AddSignIn(usuario, model.Lembrar);

            return LocalRedirect(returnUrl ?? "/");
        }
        private async void AddSignIn(Usuario usuario, bool lembraSenha = true)
        {
            var claims = new List<Claim>()
            {
                new Claim("id", usuario.IdUsuario.ToString()),
                new Claim("nome", usuario.NmUsuario),
                new Claim("email",usuario.EmailUsuario),
                new Claim("roles","admin,ti,estagiário")
            };

            var identity = new ClaimsIdentity
                (
                    claims,
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    "nome", "roles"
                );

            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(principal,
                new AuthenticationProperties
                {
                    IsPersistent = lembraSenha,
                    ExpiresUtc = DateTime.UtcNow.AddMinutes(10)
                });
        }

        [HttpGet]
        public IActionResult AddNewUser()
        {
            ViewBag.IsEditing = "N";

            UsuarioAddEditVM model = null;

            ViewBag.Title = "Adicionar Usuário";

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNewUser(string returnUrl, UsuarioAddEditVM model)
        {
            var data = model.ToData();

            data.HashSenha = model.Senha.Encrypt();
            data.DhRegistro = Convert.ToDecimal(DateTime.Now.ToString("yyyyMMddHHmmss"));
            data.StUsuario = EnumHelper.SituacaoUsuario.UA9.ToString();

            _usuarioRepo.Add(data);
            data.IdUsuarioRegistro = data.IdUsuario;

            await _uow.CommitAsync();

            await Task.Run(async () =>
            {
                int userId = Convert.ToInt32(data.IdUsuario);

                var _userToSend = new EmailFormModel()
                {
                    FromEmail = data.EmailUsuario,
                    FromName = data.NmUsuario
                };

            // Credenciais para o envio do email
            var credentials = _credential.GetEmailCredentials();

                var credEmail = credentials.Where(k => k.Key == "Email").Select(e => e.Value).ToList().FirstOrDefault();
                var credPass = credentials.Where(k => k.Key == "Password").Select(e => e.Value).ToList().FirstOrDefault();
                var credHost = credentials.Where(k => k.Key == "Host").Select(e => e.Value).ToList().FirstOrDefault();
                var credPort = credentials.Where(k => k.Key == "Port").Select(e => e.Value).ToList().FirstOrDefault();

                var _sender = new Sender(credEmail, credPass, credHost, Convert.ToInt16(credPort));

                await _sender.SendConfirmation(_userToSend, userId);
            });

            if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/") && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return View("Success", data);
            };
        }

        [HttpGet]
        public ActionResult Recover()
        {
            return View();
        }

        public async Task<JsonResult> Recover(string email)
        {
            var _login = _usuarioRepo.GetAsync().Result.FirstOrDefault(x => x.EmailUsuario == email);

            if (_login != null)
            {
                int userId = Convert.ToInt32(_login.IdUsuario);

                var _userToSend = new EmailFormModel()
                {
                    FromEmail = email,
                    FromName = _login.NmUsuario
                };

                // Credenciais para o envio do email
                var credentials = _credential.GetEmailCredentials();

                var credEmail = credentials.Where(k => k.Key == "Email").Select(e => e.Value).ToList().FirstOrDefault();
                var credPass = credentials.Where(k => k.Key == "Password").Select(e => e.Value).ToList().FirstOrDefault();
                var credHost = credentials.Where(k => k.Key == "Host").Select(e => e.Value).ToList().FirstOrDefault();
                var credPort = credentials.Where(k => k.Key == "Port").Select(e => e.Value).ToList().FirstOrDefault();

                var _sender = new Sender(credEmail, credPass, credHost, Convert.ToInt16(credPort));

                // Envia email para recuperação de senha
                await _sender.SendRecover(_userToSend, userId);

                return Json(new { status = true });
            }

            return Json(new { error = true });
        }

        public JsonResult ValidPassword(string SenhaAtual, string NovaSenha, string ConfirmaSenha)
        {
            if (NovaSenha != ConfirmaSenha)
            {
                return Json(new { error = "A nova senha não confere com a confirmação da senha" });
            }

            return Json(new { status = true });
        }

        [Route("RecoverConfirm")]
        public async Task<ActionResult> ConfirmRecover(string hash)
        {
            try
            {
                hash = CryptAES.Decrypt(hash);

                JObject json = JObject.Parse(hash);

                DateTime dateCreate = (DateTime)json["dateCreate"];
                DateTime dateExpire = (DateTime)json["dateExpire"];
                string Method = (string)json["Method"];
                decimal userId = (decimal)json["userId"];

                if (Method != "RecoverPassword")
                {
                    throw new Exception("Hash inválido para esse tipo de operação");
                }

                if (DateTime.Now > dateExpire)
                {
                    throw new Exception("Tempo limite expirado. Por favor, gere outra solicitação para recuperar a senha");
                }

                var user = await _usuarioRepo.GetAsync(userId);

                if (user == null)
                {
                    throw new Exception("Usuário inválido.");
                }

                var userVM = user.ToVM();
                userVM.Senha = "";

                return View(userVM);
            }
            catch (Exception E)
            {
                ViewBag.ErrorToConfirm = E.Message;
                return View("ErrorConfirm");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(UsuarioAddEditVM model)
        {
            if (model.Senha != model.ConfirmaSenha)
            {
                ModelState.AddModelError("", "A nova senha não confere com a confirmação da senha");
                return View("ConfirmRecover", model);
            }

            if (ModelState.IsValid)
            {
                var _usuario = await _usuarioRepo.GetAsync(model.Id);

                _usuario.HashSenha = model.Senha.Encrypt();
                _usuarioRepo.Update(_usuario);

                await _uow.CommitAsync();

                ViewBag.MessageSuccess = "Senha alterada com sucesso.";

                return View("Confirm");
            }

            return View("ConfirmRecover", model);
        }

        [Route("Confirm")]
        public ActionResult Confirm(string hash)
        {
            try
            {
                hash = CryptAES.Decrypt(hash);

                JObject json = JObject.Parse(hash);

                DateTime dateCreate = (DateTime)json["dateCreate"];
                DateTime dateExpire = (DateTime)json["dateExpire"];
                string Method = (string)json["Method"];
                int userId = (int)json["userId"];

                if (Method != "ConfirmEmail")
                {
                    throw new Exception("Hash inválido para esse tipo de operação");
                }

                if (DateTime.Now > dateExpire)
                {
                    throw new Exception("Tempo limite expirado. Por favor, gere outra chave de validação");
                }

                ViewBag.MessageSuccess = "Email confirmado com sucesso!";
                return View();
            }
            catch (Exception E)
            {
                ViewBag.ErrorToConfirm = E.Message;
                return View("ErrorConfirm");
            }

JDKB.UI/Controllers/ProdutoController.cs
using JDKB.Domain.Contracts.Data;
using JDKB.Domain.Contracts.Repositories;
using JDKB.Domain.Entities;
using JDKB.Helpers;
using JDKB.UI.Models;
using JDKB.UI.Models.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace JDKB.UI.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepository _produtoRepo;
        private readonly IUnityOfWork _uow;

        public ProdutoController(IProdutoRepository produtoRepo, IUnityOfWork uow)
        {
            _produtoRepo = produtoRepo;
            _uow = uow;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewBag.Title = "Produtos";

            ViewData["CurrentSort"] = sortOrder;
            ViewData["ProdutoSortParm"] = String.IsNullOrEmpty(sortOrder) ? "produtod" : "";
            ViewData["DescProdutoSortParm"] = sortOrder == "Produtos" ? "produto_desc" : "Produtos";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var produto = await _produtoRepo.GetAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                produto = produto.Where(s => s.CdProduto.Contains(searchString.ToUpper())
                    || s.NmProduto.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "produtod":
                    produto = produto.OrderByDescending(s => s.CdProduto);
                    break;
                case "Produtos":
                    produto = produto.OrderBy(s => s.NmProduto);
                    break;
                case "produto_desc":
                    produto = produto.OrderByDescending(s => s.NmProduto);
                    break;
                default:
                    produto = produto.OrderBy(s => s.NmProduto);
                    break;
            }

            int pageSize = 20; // Número de registros por Página

            return View(PaginatedList<Produto>.Create(produto.AsQueryable(), pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(decimal id)
        {
            ViewBag.IsEditing = "N";
            var title = "Adicionar";

            ProdutoAddEditVM model = null;

            if (id != 0)
            {
                var data = await _produtoRepo.GetAsync(id);
                if (data == null) return NotFound();

                model = data.ToVM();
                title = "Editar";
                ViewBag.IsEditing = "S";
            }

            ViewBag.Title = $"{title} Produto";

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(string id, ProdutoAddEditVM model)
        {
            ModelState.Remove("DataHoraRegistro");
            ModelState.Remove("IdUsuarioRegistro");

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var data = model.ToData();

            if (String.IsNullOrEmpty(id))
            {
                data.IdUsuarioRegistro = Convert.ToDecimal(HttpContextHelper.GetAuthUserId(HttpContext));
                data.DhRegistro = Convert.ToDecimal(DateTime.Now.ToString("yyyyMMddHHmmss"));

                _produtoRepo.Add(data);
            }
            else
            {
                _produtoRepo.Update(data);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public async Task<IActionResult> Excluir(decimal id)
        {
            var produto = await _produtoRepo.GetAsync(id);

            if (produto == null) return BadRequest();

            _produtoRepo.Remove(produto);

            await _uow.CommitAsync();

            return Ok();
        }
    }
}

JDKB.UI/Views/Shared/CustomError.cshtml
@{
    ViewBag.Title = "Erro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row text-center">
        <div class="col-sm-6 col-sm-offset-3">
            <br><br>
            <h3 class="text-danger">Erro: @ViewBag.CustomError</h3>
            <h2 class="text-danger">
                Um erro ocorreu durante o processamento.
            </h2>
            <br><br>
        </div>
    </div>
</div>

JDKB.UI/Views/Shared/_Layout.cshtml
@using JDKB.UI.Models.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/summernote/summernote.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/toastr/build/toastr.min.css" />
    <link rel="stylesheet" href="~/lib/material-design-iconic-font/css/material-design-iconic-font.min.css" />
    <link rel="stylesheet" href="~/lib/dropzone/dropzone.min.css" />
    <link rel="stylesheet" href="~/lib/dropzone/basic.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-4">
            <div class="container">
                <div class="containerlogojd">
                    <img src="~/images/Logo.png" />
                </div>

                <span><a class="navbar-brand" style="color:#dc3545; font-style:italic; margin-left:10px" asp-area="">Base de Conhecimento</a></span>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav mr-auto ">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="BaseConhecimento" asp-action="Index">Home</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cadastro</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Produto" asp-action="Index">Produtos</a>
                                    <a class="dropdown-item" asp-controller="Usuario" asp-action="Index">Usuários</a>
                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="BaseConhecimento" asp-action="About">Sobre</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">

                        @if (User.Identity.IsAuthenticated)
                        {
                            var userId = User.Claims.Where(u => u.Type == "id").FirstOrDefault();

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="spanLoggeUser">Olá <strong>@User.Identity.Name</strong></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Usuario" asp-action="AddEdit" asp-route-id="@Convert.ToDecimal(userId.Value)">Perfil</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="@Url.Action("LogOff","Auth")">Sair</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <button type="button" class="btn btn-outline-danger button-menu-right-fixed visible-xs @ViewBag.VisibleLogin"
                                        onclick="window.location.href='@Url.Action("Signin", "Auth")'">
                                    <span class="glyphicon glyphicon-log-in"></span> Login
                                </button>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>

    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <span class="text-muted">&copy;JD Consultores - @DateTime.Now.Year</span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/toastr/build/toastr.min.js"></script>
    <script src="~/lib/summernote/summernote.js"></script>
    <script src="~/lib/dropzone/dropzone.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

JDKB.UI/Views/Shared/_delModal.cshtml
<!-- Modal -->
<div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Excluir</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja excluir o(a) <span id="dataTipo"></span> <span id="nome-item" class="badge badge-secondary"></span>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger" onclick="confirmarDel()">Confirmar</button>
            </div>
        </div>
    </div>
</div>